## YAML Template.
#---
line.bot:
  channel-token: KDPIrnSbnjuvze5jDb0RQVaPbkmDiV29TFLeCBb1TbFUYTVDE63JpzXG6ZT50kcEn1CiQDZUgCYhQFfFx7XPM4CQ74H7k6XExrqfnsaCkRffcTq++U8w2rA6lligH3lXkkL2xefjobvEIwwKyiN8IQdB04t89/1O/w1cDnyilFU=
  channel-secret: 3124c77394b138c2c7e0496c952fd0e9
  handler.path: /callback
  

spring:
  resources:
    static-locations: classpath:/static/,classpath:/images/,file:D:/RUNJAR/JAVA/images2/ 
  mvc:
    static-path-pattern: /images/**
  thymeleaf:
    cache: false
#    prefix: classpath:/templates/,classpath:/static/,classpath:/images/
#    suffix: .html
#    encoding: UTF-8
#    mode: HTML5 


#
##新增那個目錄的檔案需要restart
#devtools:
#    restart:
#    #热部署生效
#    enabled: true
#    #设置重启的目录
#    additional-paths: classpath:/static/,classpath:/images/
##    additional-paths: resources/**,static/**,templates/**
#    #该目录下的内容修改不重启
#    exclude: data/**
#devtools:
#    restart:
#      additional-paths: classpath:/templates/,classpath:/static/,classpath:/images/



 
# 排除那個目錄的檔案不需要restart
# spring.devtools.restart.exclude=static/**,public/**

    
#server:
#  servlet:
#    context-path: /BESSIE
#  port: 2080
